### ISSUE TITLE
erlang install is broken because it's not allowed to bind to 0.0.0.0 or 127.0.0.1 on OpenShift

### ISSUE THREAD

**Issue by kaosko** [marianoguerra/couchdb-for-openshift#9]
(Already mentioned in the comments for issue #8). The current erlang install is broken because it tries to bind to port 0.0.0.0 and that is not allowed on OpenShift. The main problem for couchdb is that replicating a remote database fails because of this issue. The issue is also described at http://blog.pyjeon.com/2013/11/07/erlang-ejabberd-on-openshift/. Just as a test, I made a recursive replace on all sources 

    find . -type f -print0 | xargs -0 sed -i 's/{0,0,0,0}/'"{${OPENSHIFT_DIY_IP//[.]/,}}"'/g'

After install, **erlang/bin/epmd  -address $OPENSHIFT_DIY_IP -debug** still fails on "permission denied but 

    httpc:request(get, {"http://www.erlang.org", []}, [], []).
fails on etimedout and

    erlang/bin/erl -sname my_name
fails on "Failed to create cookie file '/var/lib/openshift/b8d46b3b0000a3/.erlang.cookie", which is probably the easiest to fix. If you modify the sources carefully it seems like it'd be  possible to get it to run properly but I don't pretend to understand erlang well enough so not going to attempt it.

**Comment by marianoguerra** [comment]
please reopen if this still happens.

**Comment by MrTrick** [comment]
This is an issue for me as well - was this solved by some revision?

**Comment by axelingadi** [comment]
+ 1

**Comment by marianoguerra** [comment]
I haven't used couchdb on openshift for a long while, I just keep it updated if it's easy, in this case I would need more help from people actually using it. 

if someone is interested in taking over this I would be more than happy to help you.
